### Root Endpoint
GET http://localhost:5000/

### User Signup
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "monita123test1",
  "email": "test21@example.com",
  "password": "password123456"
}

### User Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "test21@example.com",
  "password": "password123456"
}


### post user profile
POST http://localhost:5000/users/profile
Content-Type: application/json

{
  "favorite_genres": "favoriteGenres",
  "reading_preferences": "readingPreferences",
  "books_owned": "booksOwned",
  "books_wanted": "booksWanted"
}

### Get User Profile (Protected Route)
GET http://localhost:5000/user/profile
Authorization: Bearer {{token}}

### Forgot Password
POST http://localhost:5000/auth/forgot-password
Content-Type: application/json

{
  "email": "mon1233@example.com"
}

###
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJtb24xQGV4YW1wbGUuY29tIiwiaWF0IjoxNzMxNzYzOTQ4fQ.KW5719OUbaaSY1FdtzQ-tZ2lvU7r-HB5_XWDdkWDpGY
### Reset Password
POST http://localhost:5000/auth/reset-password
Content-Type: application/json

{
  "token": "{{token}}",
  "newPassword": "newpassword123"
}

### Create Book
POST http://localhost:5000/books
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald"
}

### Get Books
GET http://localhost:5000/books

### Get Book by ID
GET http://localhost:5000/books/3

### Update Book
PUT http://localhost:5000/books/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald new"
}

### Delete Book
DELETE http://localhost:5000/books/5
Authorization: Bearer {{token}}